language: node_js
node_js:
  - "lts/*"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href https://lukecmstevens.co.uk/vintage-computing
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/vintagecomputing
  on:
branch: master
